---
title: "tasks"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{tasks}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  eval = FALSE,
  collapse = TRUE,
  comment = "#>"
)
```

This **tasks** section contains a list of tasks and questions, with their current status

-   ✔️ completed
-   ❗ awaiting completion
-   ✖️no longer needed
-   ❓question to be answered

## Tasks and questions

### 2022-06-17

-   ❓Change colour of fileInput control progress bar to green.

-   ❓Change colour of input control sliders to green.

-   ❓Change text colour of actionbuttons to white.

-   ❓Change colour of datatable buttons to green.

-   ❓Change notification background colour to green.

-   ❗Use shiny tour guide in multi-tabbed shiny dashboard, shiny modules and golem. [Cicerone not working with shinydashboard multitabs](https://github.com/JohnCoene/cicerone/issues/21)

### 2022-06-15

Managing Fire Risk Tool

-   ❓Leaflet mapping control

-   ❓Language control

-   ❓Collapsible sections in sidebar

CUU Habitat Change analysis

-   ❓Shiny in R markdown

### 2022-06-10

-   ❓Joe Chang RStudio 2019 talk [Shiny in production: Principles, practices, and tools](https://www.rstudio.com/resources/rstudioconf-2019/shiny-in-production-principles-practices-and-tools/) and [Scaling an app](https://rstudio.github.io/shinyloadtest/articles/case-study-scaling.html) case study

-   ❓Alan Dipert RStudio 2018 talk [Make Shiny Fast by Doing as Little Work as Possible](https://www.rstudio.com/resources/rstudioconf-2018/make-shiny-fast-by-doing-as-little-work-as-possible/)

### 2022-06-09

-   ❗ Issue with UI filter drop-down boxes do not populate if filter menu has not been previously selected
-   ❓setting observeEvent parameter ignoreInit or ignoreNULL to TRUE to ignore initial change in Event.

### 2022-06-01

Update [UI shinydashboard](https://rstudio.github.io/shinydashboard/structure.html)

-   ❓Use messages, notifications and tasks in header menu.

-   ❓Dynamically generate sidebar menus

-   ❓Add background colour to box

-   ❓Use tabBoxes

-   ❓Add infoBoxes and valueBoxes

-   ❓Add custom css

### 2022-05-04

-   ✔️ Read [Creating a Shiny App for Database Management](https://shanghai.hosting.nyu.edu/data/r/case-4-database-management-shiny.html) blog post

-   ✖️Add bookmark button: Mastering Shiny page 180.

-   ✖️Download a parameterized report: Mastering Shiny page 146.

-   ✖️Colour selected plot points using brushed points: Mastering Shiny page 113.
